name: list_with_scrollable_header
description: Package criado inspirado nas listas dos principais apps de pedidos, com uma lista com índice scrollable.
version: 0.0.1
author: Leonardo Benedeti
homepage: https://github.com/leonardobenedeti/list_with_scrollable_header

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: